languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Congo"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params]
  # mainSections = ["section1", "section2"]

[author]
  name = "Jordan Sell"
  image = "img/author.jpg"
  headline = "Hey, welcome to my site!"
  bio = "I write code sometimes.  Hit me up on my linkedin!"
  links = [
    { email = "jordanjsell@gmail.com" },
    { github = "https://github.com/jordanjsell" },
    { linkedin = "https://linkedin.com/in/jordanjsell" },
    { twitter = "https://twitter.com/jordanjsell" },
  ]
